# Generated by Django 4.2.7 on 2023-11-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
